### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by jdiaz97** [jdiaz97/wherearethe.games#4]
- [x] Add a bit more data - Will do soon
- [x] Have fully clean Julia pipelines - Will do soon
- [x] Refactor Julia code, make more simple - Will do soon
- [x] Fix "All Years" filter so it's ordered correctly, sometimes dates can be like [2020, 2016, To be announced, 2018]
- [ ] Add "Articles" page section - Will do soon
- [ ] Add "Order by date" functionality 

The sites should be static. Right now, they are dynamic. So we need:
- [ ] Static map section
- [ ] Static country page
